name: 'VBA Code Scanner'
description: 'A code scanning tool built for the Swissgrid AG.'
author: 'Benjamin OSullivan'
inputs:
  reportType:
    description: 'Either User or Reviewer, decided how the report is structured.'
    default: 'User'
  dirPath:
    description: 'The directory containing the repository that is to be searched.'
    default: './'
outputs:
  report:
    description: 'A file list all violations '

runs:
  using: "docker"
  image: "Dockerfile"
