name: 'VBA Code Scanner'
description: 'A code scanning tool built for the Swissgrid AG.'
author: 'Benjamin OSullivan'
inputs:
  reportType:
    required: True
    description: 'Either User or Reviewer, decided how the report is structured.'
    default: 'User'
  dirPath:
    required: True
    description: 'The directory containing the repository that is to be searched.'
    default: './'
outputs:
  report:
    description: 'A file list all violations'

runs:
  # using: "docker"
  # image: "Dockerfile"
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
      
    - uses: actions/checkout@v4
      with: 
        repository: benosul/SomeTests
        
    - run: ls -a
      shell: bash

    - name: Main
      run: python main.py ${{ inputs.dirPath }} ${{ inputs.reportType }}
      shell: bash
