name: Run Some Tests
on:
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Access To PAT
        run: |
          echo ${{ secrets.PACKAGE_PAT }} | docker login ghcr.io -u benosul --password-stdin

      - name: Test Docker Pull
        run: |
          docker pull ghcr.io/benosul/sometests@sha256:03719957ce25d3bb4a23cd9ac3dcad02a9b5bdb82c3cdd294857ea0a7b679b08
          docker build -t sometests .
          docker run sometests 

      - name: Sanity Check
        run: ls -a 
