name: Run Some Tests
on:
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Access To PAT
        run: |
          echo ${{ secrets.PACKAGE_PAT }} | docker login ghcr.io -u benosul --password-stdin

      - name: Test Docker Pull
        run: |
          docker pull ghcr.io/benosul/sometests:main

      - name: Run Docker Image
        run: |
          docker run -d --name testImage ghcr.io/${{ github.actor }}/sometests:main "User"
          
      - name: Review Docker Logs
        run: |
          docker logs testImage

      - name: Copy file from docker image
        run: |
          docker cp testImage:report.txt .
          docker cp testImage:report.log .
        
      - name: Sanity Check
        run: ls -a

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Report
          path: report.txt, report.log
