name: Run Some Tests
on:
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.PACKAGE_PAT }} | docker login -u ${{ github.actor }} --password-stdin ghcr.io

      - name: Test Docker Pull
        run: |
          docker pull ghcr.io/benosul/sometests:main
          docker build -t sometests .
          docker run sometests 
