name: Run Some Tests
on:
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Access To PAT
        run: |
          echo ${{ secrets.PACKAGE_PAT }} | docker login ghcr.io -u benosul --password-stdin

      - name: Test Docker Pull
        run: |
          docker pull ghcr.io/benosul/sometests:main
          docker build -t sometests .
          docker run sometests "abc"

      - name: Sanity Check
        run: ls -a 
