name: Pull Package from GitHub Container Registry
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  pull-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.PACKAGE_PAT }} | docker login -u ${{ github.actor }} --password-stdin ghcr.io

      - name: Pull Package
        run: docker pull ghcr.io/benosul/sometests:main

      - name: Sanity Check
        run: ls -a

      - name: Run Docker
        env:
          ARG1: "123"
          ARG2: "abc"
          ARG3: "zyx"
        run: docker run -e ARG1 -e ARG2 -e ARG3  
